apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: mycreds
spec:
  serviceClassName: hashicorp-vault
  planName: shared
---
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
metadata:
  name: mycreds
spec:
  instanceRef:
    name: mycreds
  secretName: mycreds