apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Broker
metadata:
  name: vault-broker
spec:
  url: http://cf-vault-service-broker.catalog.svc.cluster.local:8000
  # put the basic auth for the broker in a secret, and reference the secret here.
  # service-catalog will use the contents of the secret. The secret should have "username"
  # and "password" keys
  authInfo:
    basicAuthSecret:
      namespace: catalog
      name: vault